<?php

/* 
 * @file Hello Module
 */

function hello_block_info() {
  $blocks['hello'] = array(
    'info' => t('Hello World Block'),
  );
  
  return $blocks;
}

function hello_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'hello':
      $block['subject'] = t('Hello World');
      
      
      
      $hour = date('G');
      $greeting = '';
      if ($hour < 12) {
        $greeting = t('Good morning @name!');
      }
      elseif ($hour < 18) {
        $greeting = t('Good afternoon @name!');
      }
      else {
        $greeting = t('Good evening @name!');
      }
      $block['content'] = '<p>' . t($greeting, array('@name' => $GLOBALS['user']->name)) . '</p>';
      
      if (module_exists('devel')) {
        dpm($_GET);
        dpm(arg(0));
        dpm(arg(1));
      }
      if (arg(0) == 'node' && is_numeric(arg(1))) {
        $block['content'] .= '<p>' . t('You are on a node page.') . '</p>';
      }
      if (arg(0) == 'user' && is_numeric(arg(1))) {
        $block['content'] .= '<p>' . t('You are on a user page.') . '</p>';
      }
      
      
      break;
  }
  
  return $block;
}