<?php

/*
 * @file Hello Module
 */

function hello_block_info() {
  $blocks['hello_user'] = array(
    'info' => t('Hello World User Block'),
  );
  
  return $blocks;
}

function hello_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'hello_user':
      if (arg(0) == 'user' && is_numeric(arg(1))) {
        $block['subject'] = t('User Details');
        $account = user_load(arg(1));
        if (!empty($account)) {
          $output = '';
          $output .= '<div><label>' . t('Name') . ': </label>' . $account->name . '</div>'; 
          $output .= '<div><label>' . t('Email') . ': </label>' . $account->mail . '</div>';
          $output .= '<div><label>' . t('Created') . ': </label>' . format_date($account->created) . '</div>'; 
          $output .= '<div><label>' . t('Last Access') . ': </label>' . 
            (($account->access == 0) ? t('Never') : format_date($account->access)) . '</div>';
          $block['content'] = $output;
        }
      }
      break;
  }

  return $block;
}