<?php

/* 
 * @file Menu Router Examples
 */

/**
 * Implements hook_menu()
 * 
 * @return array
 */
function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    'title' => 'Hello World',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'weight' => 2,
  );
  
  $items['hello/simple'] = array(
    'title' => 'Simple',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['hello/variables'] = array(
    'title' => 'Hello Variables',
    'description' => 'Print the values of system variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );
  
  $items['hello/variables/%'] = array(
    'title callback' => 'hello_menu_show_variable_title',
    'title arguments' => array(2),
    'page callback' => 'hello_menu_show_variable',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'weight' => 4,
  );
  
  $items['hello/variables/create'] = array(
    'title' => 'Create Variable',
    'description' => 'Create system variable',
    'page callback' => 'hello_menu_create_variable',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_ACTION,
  );
  
  return $items;
}

function hello_menu_create_variable() {
  return t('Here is where we create variables.');
}

function hello_menu_show_variable_title($variable_name) {
  return t('Show Variable: @name', array('@name' => $variable_name));
}

function hello_menu_show_variable($variable_name) {
  return variable_get($variable_name, t('No value for this variable'));
}

/**
 * Returns a list of system variables.
 * 
 */
function hello_menu_list_variables() {
  $variables = variable_initialize();
  $names = array_keys($variables);
  $output = '<ul>';
  foreach ($names as $name) {
    $output .= '<li>' . l($name, 'hello/variables/' . $name) . '</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Simple Hello World page.
 * @return string
 */
function hello_menu_simple_hello() {
  return t('Hello world!!');
}