<?php

/* 
 * @file Menu Router Examples
 */

/**
 * Implements hook_menu()
 * 
 * @return array
 */
function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    'title' => 'Hello World',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'weight' => 2,
  );
  
  $items['variables'] = array(
    'title' => 'Hello Variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'weight' => 3,
  );
  
  $items['variables/site_name'] = array(
    'title' => 'Hello Variables: Site Name',
    'page callback' => 'hello_menu_show_variable',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'weight' => 4,
  );
  
  return $items;
}

function hello_menu_show_variable() {
  return variable_get('site_name', t('No value for this variable'));
}

/**
 * Returns a list of system variables.
 * 
 */
function hello_menu_list_variables() {
  $variables = variable_initialize();
  $names = array_keys($variables);
  $output = '<ul>';
  foreach ($names as $name) {
    $output .= '<li>' . $name . '</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Simple Hello World page.
 * @return string
 */
function hello_menu_simple_hello() {
  return t('Hello world!!');
}