<?php

/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function node_metadata_menu() {
  $items = array();
  
  $items['node/%/metadata'] = array(
    'title' => 'Metadata',
    'page callback' => 'node_metadata_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

function node_metadata_page($nid) {
  $node = node_load($nid);
  $output = '';
  $output .= '<div><label>Author:</label> ' .  $node->name . '</div>';
  $output .= '<div><label>Created:</label>' . format_date($node->created) . '</div>';
  $output .= '<div><label>Updated:</label>' . format_date($node->changed) . '</div>';
  $output .= '<div><label>Comment Count:</label>' . $node->comment_count . '</div>';
  return $output;
}