<?php

/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function node_metadata_menu() {
  $items = array();
  
  $items['node/%node/metadata'] = array(
    'title' => 'Metadata',
    'page callback' => 'node_metadata_page',
    'page arguments' => array(1),
    'access arguments' => array('view node metadata'),
    'file' => 'node_metadata.pages.inc',
    'file path' => drupal_get_path('module', 'node_metadata'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

function node_metadata_permission() {
  return array(
    'view node metadata' => array(
      'title' => t('View node metadata'),
      'description' => t('View metadata about nodes on a subtab.'),
    ),
  );
}