<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

define('NODE_LIMIT_MAX_EDIT_TIME', 900);

function node_limit_menu_alter(&$items) {
  $items['node/%node/edit']['title callback'] = 'node_limit_node_edit_title';
  $items['node/%node/edit']['title arguments'] = array(1);
  $items['node/%node/edit']['weight'] = -1;
  $items['node/%node/edit']['access callback'] = 'node_limit_node_access';
}

function node_limit_node_edit_title($node) {
  $time_diff = REQUEST_TIME - $node->changed;
  $time_left = round((NODE_LIMIT_MAX_EDIT_TIME - $time_diff) / 60);
  
  return t('Update (@time minutes)', array('@time' => $time_left));
}

function node_limit_node_access($op, $node) {
  if ($node->changed > (REQUEST_TIME - NODE_LIMIT_MAX_EDIT_TIME)) {
    return node_access($op, $node);
  }
  return FALSE;
}